# Generated by Django 5.2.6 on 2025-09-20 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'verbose_name': 'سنة دراسية', 'verbose_name_plural': 'سنوات دراسية'},
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'واجب', 'verbose_name_plural': 'واجبات'},
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'سجل حضور', 'verbose_name_plural': 'سجلات الحضور'},
        ),
        migrations.AlterModelOptions(
            name='classsession',
            options={'verbose_name': 'حصة', 'verbose_name_plural': 'حصص'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'تسجيل', 'verbose_name_plural': 'تسجيلات'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'مجموعة', 'verbose_name_plural': 'مجموعات'},
        ),
        migrations.AlterModelOptions(
            name='homeworksubmission',
            options={'verbose_name': 'تسليم واجب', 'verbose_name_plural': 'تسليمات الواجبات'},
        ),
        migrations.AlterModelOptions(
            name='monthlyreport',
            options={'verbose_name': 'تقرير شهري', 'verbose_name_plural': 'تقارير شهرية'},
        ),
        migrations.AlterModelOptions(
            name='parentprofile',
            options={'verbose_name': 'وليّ الأمر', 'verbose_name_plural': 'أولياء الأمور'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'مورد', 'verbose_name_plural': 'موارد'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'طالب', 'verbose_name_plural': 'طلاب'},
        ),
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'verbose_name': 'ملف المدرّس', 'verbose_name_plural': 'ملفات المدرّسين'},
        ),
        migrations.AlterModelOptions(
            name='weeklyscheduleblock',
            options={'verbose_name': 'بلوك جدول أسبوعي', 'verbose_name_plural': 'بلوكات الجدول الأسبوعي'},
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='end_date',
            field=models.DateField(verbose_name='تاريخ النهاية'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعّلة؟'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اسم السنة'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='start_date',
            field=models.DateField(verbose_name='تاريخ البداية'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإسناد'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='assignments/', verbose_name='مرفق'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف الواجب'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسليم'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.group', verbose_name='المجموعة'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='points',
            field=models.PositiveIntegerField(default=100, verbose_name='الدرجة الكاملة'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان الواجب'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='ملاحظة'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='core.classsession', verbose_name='الحصة'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'حاضر'), ('ABSENT', 'غائب'), ('LATE', 'متأخّر'), ('EXCUSED', 'معذور')], default='PRESENT', max_length=10, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='core.student', verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='end_time',
            field=models.TimeField(verbose_name='وقت النهاية'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.group', verbose_name='المجموعة'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='is_online',
            field=models.BooleanField(default=True, verbose_name='أونلاين؟'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='meeting_link',
            field=models.URLField(blank=True, verbose_name='رابط الحصة'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='start_time',
            field=models.TimeField(verbose_name='وقت البداية'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.teacherprofile', verbose_name='المدرّس'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='topic',
            field=models.CharField(blank=True, max_length=200, verbose_name='الموضوع'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.group', verbose_name='المجموعة'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشِط؟'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='joined_on',
            field=models.DateField(auto_now_add=True, verbose_name='تاريخ الانضمام'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.student', verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='group',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.academicyear', verbose_name='السنة الدراسية'),
        ),
        migrations.AlterField(
            model_name='group',
            name='capacity',
            field=models.PositiveIntegerField(default=30, verbose_name='السعة'),
        ),
        migrations.AlterField(
            model_name='group',
            name='grade',
            field=models.CharField(choices=[('G1', 'الصف الرابع'), ('G2', 'الصف الخامس'), ('G3', 'الصف 1 اعدادي'), ('G4', 'الصف 2 اعدادي'), ('G5', 'الصف 3 اعدادي'), ('OTHER', 'أخرى')], max_length=10, verbose_name='الصف الدراسي'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم المجموعة'),
        ),
        migrations.AlterField(
            model_name='group',
            name='note',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='core.teacherprofile', verbose_name='المدرّس'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='answer_text',
            field=models.TextField(blank=True, verbose_name='نص الإجابة'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.assignment', verbose_name='الواجب'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='تعليق المدرّس'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='file',
            field=models.FileField(blank=True, upload_to='submissions/', verbose_name='ملف مرفوع'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الدرجة'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='link',
            field=models.URLField(blank=True, verbose_name='رابط الإجابة'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'مُسلَّم'), ('GRADED', 'مصحّح'), ('LATE', 'متأخّر')], default='SUBMITTED', max_length=10, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.student', verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت التسليم'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='attendance_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الحضور'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='avg_homework_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='متوسط درجة الواجب'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='month',
            field=models.PositiveIntegerField(verbose_name='الشهر'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='recommendations',
            field=models.TextField(blank=True, verbose_name='توصيات'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='strengths',
            field=models.TextField(blank=True, verbose_name='نِقَاط القوة'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='core.student', verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='teacher_comment',
            field=models.TextField(blank=True, verbose_name='تعليق المدرّس العام'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='weaknesses',
            field=models.TextField(blank=True, verbose_name='نِقَاط الضعف'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='year',
            field=models.PositiveIntegerField(verbose_name='السنة'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, upload_to='resources/', verbose_name='ملف'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.group', verbose_name='مجموعة'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='kind',
            field=models.CharField(choices=[('VIDEO', 'رابط فيديو'), ('FILE', 'ملف مرفوع'), ('LINK', 'رابط خارجي'), ('NOTE', 'ملاحظة')], default='VIDEO', max_length=10, verbose_name='نوع المورد'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.classsession', verbose_name='حصة'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=200, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True, verbose_name='رابط'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=60, verbose_name='الاسم الأول'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=60, verbose_name='اسم العائلة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.parentprofile', verbose_name='وليّ الأمر'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='اسم المدرسة'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='weeklyscheduleblock',
            name='end_time',
            field=models.TimeField(verbose_name='وقت النهاية'),
        ),
        migrations.AlterField(
            model_name='weeklyscheduleblock',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_blocks', to='core.group', verbose_name='المجموعة'),
        ),
        migrations.AlterField(
            model_name='weeklyscheduleblock',
            name='is_online',
            field=models.BooleanField(default=True, verbose_name='أونلاين؟'),
        ),
        migrations.AlterField(
            model_name='weeklyscheduleblock',
            name='location',
            field=models.CharField(blank=True, max_length=120, verbose_name='الموقع/العنوان'),
        ),
        migrations.AlterField(
            model_name='weeklyscheduleblock',
            name='meeting_link',
            field=models.URLField(blank=True, verbose_name='رابط الحصة'),
        ),
        migrations.AlterField(
            model_name='weeklyscheduleblock',
            name='start_time',
            field=models.TimeField(verbose_name='وقت البداية'),
        ),
        migrations.AlterField(
            model_name='weeklyscheduleblock',
            name='weekday',
            field=models.IntegerField(choices=[(1, 'الاثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس'), (5, 'الجمعة'), (6, 'السبت'), (7, 'الأحد')], verbose_name='اليوم'),
        ),
    ]
