# Generated by Django 5.2.6 on 2025-09-20 16:12

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_academicyear_options_alter_assignment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalHomeworkSubmission',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, verbose_name='وقت التسليم')),
                ('answer_text', models.TextField(blank=True, verbose_name='نص الإجابة')),
                ('file', models.TextField(blank=True, max_length=100, verbose_name='ملف مرفوع')),
                ('link', models.URLField(blank=True, verbose_name='رابط الإجابة')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الدرجة')),
                ('feedback', models.TextField(blank=True, verbose_name='تعليق المدرّس')),
                ('status', models.CharField(choices=[('SUBMITTED', 'مُسلَّم'), ('GRADED', 'مصحّح'), ('LATE', 'متأخّر')], default='SUBMITTED', max_length=10, verbose_name='الحالة')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assignment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.assignment', verbose_name='الواجب')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'سجل التغييرات',
                'verbose_name_plural': 'historical تسليمات الواجبات',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
