# Generated by Django 5.2.6 on 2025-09-20 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historicalhomeworksubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ASSIGNMENT_CREATED', 'إنشاء واجب'), ('SESSION_REMINDER', 'تذكير حصة')], max_length=40)),
                ('object_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'object_id', 'recipient'], name='core_notifi_event_t_1cf7ad_idx')],
                'unique_together': {('event_type', 'object_id', 'recipient')},
            },
        ),
    ]
