# Generated by Django 5.2.6 on 2025-09-20 20:33

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notificationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhomeworksubmission',
            name='file',
            field=models.TextField(blank=True, max_length=100, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg']), core.validators.validate_mime, core.validators.MaxFileSizeValidator(50)], verbose_name='ملف مرفوع'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='file',
            field=models.FileField(blank=True, upload_to='submissions/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg']), core.validators.validate_mime, core.validators.MaxFileSizeValidator(50)], verbose_name='ملف مرفوع'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, upload_to='resources/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg']), core.validators.validate_mime, core.validators.MaxFileSizeValidator(50)], verbose_name='ملف'),
        ),
    ]
