# Generated by Django 5.2.6 on 2025-09-20 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_historicalhomeworksubmission_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المادة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='لون اختياري (hex)')),
            ],
            options={
                'verbose_name': 'مادة',
                'verbose_name_plural': 'مواد',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject', verbose_name='المادة'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject', verbose_name='المادة'),
        ),
        migrations.AddField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject', verbose_name='المادة (افتراضي)'),
        ),
        migrations.AddField(
            model_name='resource',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject', verbose_name='المادة'),
        ),
    ]
