# Generated by Django 5.2.6 on 2025-09-20 21:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_subject_assignment_subject_classsession_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='سنة الفاتورة')),
                ('month', models.IntegerField(verbose_name='شهر الفاتورة')),
                ('amount_egp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ بالجنيه')),
                ('status', models.CharField(choices=[('DUE', 'مستحق'), ('PAID', 'مدفوع'), ('OVERDUE', 'متأخّر'), ('CANCELED', 'ملغاة')], default='DUE', max_length=10, verbose_name='الحالة')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ السداد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.group', verbose_name='المجموعة')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.parentprofile', verbose_name='وليّ الأمر')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'فواتير',
                'ordering': ['-year', '-month', '-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_egp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ بالجنيه')),
                ('method', models.CharField(choices=[('CASH', 'نقدي'), ('TRANSFER', 'تحويل بنكي'), ('OTHER', 'أخرى')], default='CASH', max_length=10, verbose_name='طريقة الدفع')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='رقم مرجع/إيصال')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الاستلام')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.invoice', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'سداد',
                'verbose_name_plural': 'مدفوعات',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['parent', 'status'], name='core_invoic_parent__bf644c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['year', 'month'], name='core_invoic_year_d09c82_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('parent', 'student', 'group', 'year', 'month')},
        ),
    ]
