# Generated by Django 5.2.6 on 2025-09-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_invoice_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name="classsession",
            name="qr_token",
            field=models.CharField(blank=True, max_length=64, verbose_name="توكن QR"),
        ),
        migrations.AddField(
            model_name="classsession",
            name="qr_token_expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="انتهاء التوكن"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="checkin_code",
            field=models.CharField(
                blank=True, null=True, max_length=12, verbose_name="كود الحضور"
            ),
        ),
    ]
