# Generated by Django 5.2.6 on 2025-09-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_classsession_qr_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='checkin_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='كود الحضور'),
        ),
    ]
