# Generated by Django 5.2.6 on 2025-09-27 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groupssubject', to='core.subject', verbose_name='المادة (افتراضي)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachergroups', to='core.teacherprofile', verbose_name='المدرّس'),
        ),
    ]
