# Generated by Django 5.2.6 on 2025-09-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_group_subject_alter_group_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grade',
            field=models.CharField(choices=[('G1', 'الصف 1 الابتدائي'), ('G2', 'الصف 2 الابتدائي'), ('G3', 'الصف 3 الابتدائي  '), ('G4', 'الصف 4 الابتدائي'), ('G5', 'الصف 5 الابتدائي'), ('G6', 'الصف 1 الاعدادي'), ('G7', 'الصف 2 الاعدادي'), ('G8', 'الصف 3 الاعدادي'), ('G9', 'الصف 1 الثانوي'), ('G10', 'الصف 2 الثانوي'), ('G11', 'الصف 3 الثانوي'), ('OTHER', 'أخرى')], max_length=10, verbose_name='الصف الدراسي'),
        ),
    ]
